package main

import (
	"encoding/json"
	"fmt"
	"strings"
	"unicode"
)

type responseLanguagePreference struct {
	Code   string `json:"code"`
	Name   string `json:"name"`
	Source string `json:"source"`
}

const responseLanguageSystemPrefix = "DAIKI RESPONSE LANGUAGE:"

func isAutomaticAttachmentPrompt(text string) bool {
	n := strings.ToLower(strings.TrimSpace(text))
	n = strings.TrimSuffix(n, ".")
	switch n {
	case "please review the attached content", "please review the attached file", "please review the attached image", "review the attached content", "review attached content":
		return true
	default:
		return false
	}
}

func explicitResponseLanguage(text string) responseLanguagePreference {
	n := strings.ToLower(strings.TrimSpace(text))
	checks := []struct {
		code string
		name string
		keys []string
	}{
		{"th-TH", "Thai", []string{"ตอบเป็นภาษาไทย", "ตอบภาษาไทย", "ตอบไทย", "ใช้ภาษาไทย", "reply in thai", "respond in thai", "answer in thai"}},
		{"en", "English", []string{"ตอบเป็นภาษาอังกฤษ", "ตอบภาษาอังกฤษ", "ตอบอังกฤษ", "ใช้ภาษาอังกฤษ", "reply in english", "respond in english", "answer in english"}},
		{"zh", "Chinese", []string{"ตอบเป็นภาษาจีน", "ตอบภาษาจีน", "ตอบจีน", "ใช้ภาษาจีน", "reply in chinese", "respond in chinese", "answer in chinese"}},
		{"ja", "Japanese", []string{"ตอบเป็นภาษาญี่ปุ่น", "ตอบภาษาญี่ปุ่น", "reply in japanese", "respond in japanese", "answer in japanese"}},
		{"ko", "Korean", []string{"ตอบเป็นภาษาเกาหลี", "ตอบภาษาเกาหลี", "reply in korean", "respond in korean", "answer in korean"}},
	}
	for _, check := range checks {
		for _, key := range check.keys {
			if strings.Contains(n, key) {
				return responseLanguagePreference{Code: check.code, Name: check.name, Source: "explicit"}
			}
		}
	}
	return responseLanguagePreference{}
}

func detectTextLanguage(text string) responseLanguagePreference {
	var thai, latin, han, kana, hangul int
	for _, r := range text {
		switch {
		case r >= '\u0E00' && r <= '\u0E7F':
			thai++
		case r >= '\u3040' && r <= '\u30FF':
			kana++
		case r >= '\uAC00' && r <= '\uD7AF':
			hangul++
		case unicode.In(r, unicode.Han):
			han++
		case unicode.IsLetter(r) && r <= unicode.MaxLatin1:
			latin++
		}
	}
	// Script-specific languages win over incidental Latin identifiers in a turn.
	if thai >= 2 && thai >= kana && thai >= hangul {
		return responseLanguagePreference{Code: "th-TH", Name: "Thai", Source: "conversation"}
	}
	if kana >= 2 {
		return responseLanguagePreference{Code: "ja", Name: "Japanese", Source: "conversation"}
	}
	if hangul >= 2 {
		return responseLanguagePreference{Code: "ko", Name: "Korean", Source: "conversation"}
	}
	if han >= 2 && han > thai {
		return responseLanguagePreference{Code: "zh", Name: "Chinese", Source: "conversation"}
	}
	if latin >= 4 {
		return responseLanguagePreference{Code: "en", Name: "English", Source: "conversation"}
	}
	return responseLanguagePreference{}
}

func resolveResponseLanguage(body []byte) responseLanguagePreference {
	var payload map[string]any
	if json.Unmarshal(body, &payload) != nil {
		return responseLanguagePreference{}
	}
	messages, _ := payload["messages"].([]any)
	for i := len(messages) - 1; i >= 0; i-- {
		m, _ := messages[i].(map[string]any)
		if m == nil || strings.ToLower(strings.TrimSpace(fmt.Sprint(m["role"]))) != "user" {
			continue
		}
		text := messagePlainText(m)
		if text == "" {
			continue
		}
		if explicit := explicitResponseLanguage(text); explicit.Code != "" {
			return explicit
		}
		// This sentence is generated by the Daiki composer when the user attaches a
		// file without typing. It must not switch a Thai conversation to English.
		if isAutomaticAttachmentPrompt(text) {
			continue
		}
		if detected := detectTextLanguage(text); detected.Code != "" {
			return detected
		}
	}
	return responseLanguagePreference{}
}

func languageInstruction(pref responseLanguagePreference) string {
	if pref.Code == "" {
		return ""
	}
	return fmt.Sprintf(`%s The active conversation language is %s (%s). Reply in %s unless the user explicitly asks to switch languages. An automatic attachment-review sentence may be English; it is language-neutral and must not change the conversation language. Keep filenames, code, identifiers, CSV/Excel column names, URLs, and quoted source text in their original form when useful, but write explanations, headings, summaries, caveats, and recommendations in %s. Do not switch to another language merely because an attachment contains foreign-language text.`, responseLanguageSystemPrefix, pref.Name, pref.Code, pref.Name, pref.Name)
}

func applyResponseLanguage(body []byte) ([]byte, responseLanguagePreference, error) {
	pref := resolveResponseLanguage(body)
	if pref.Code == "" {
		return body, pref, nil
	}
	var payload map[string]any
	if err := json.Unmarshal(body, &payload); err != nil {
		return nil, pref, err
	}
	messages, ok := payload["messages"].([]any)
	if !ok {
		return body, pref, nil
	}
	filtered := make([]any, 0, len(messages)+1)
	for _, raw := range messages {
		m, _ := raw.(map[string]any)
		if m != nil && strings.EqualFold(strings.TrimSpace(fmt.Sprint(m["role"])), "system") && strings.HasPrefix(strings.TrimSpace(messagePlainText(m)), responseLanguageSystemPrefix) {
			continue
		}
		filtered = append(filtered, raw)
	}
	payload["messages"] = append([]any{map[string]any{"role": "system", "content": languageInstruction(pref)}}, filtered...)
	out, err := json.Marshal(payload)
	return out, pref, err
}
